const CAMPUS_BUILDINGS = [
  {
    id: "ab1",
    name: "Academic Block 1 (AB1)",
    category: "academic",
    catLabel: "Academic",
    icon: "🏛️",
    tagline: "Main Academic Complex & Auditorium",
    desc: "Primary academic block featuring multi-colored panel facade (terracotta, beige & slate gray), central entrance portico with white VIT structure, smart classrooms, computer science labs, and the 600-seat auditorium.",
    x: 760,
    y: 165,
    hours: "8:00 AM - 8:00 PM",
    facilities: "Auditorium, Computer Labs, Deans' Offices, Smart Classrooms, Exam Cell",
    styleType: "ab1-real",
    gmapsQuery: "Academic Block 1 AB1 VIT Bhopal University"
  },
  {
    id: "ab2",
    name: "Academic Block 2 (AB2)",
    category: "academic",
    catLabel: "Academic",
    icon: "🏫",
    tagline: "Engineering Wing & Research Labs",
    desc: "Houses mechanical, electrical, and civil engineering laboratories, research centres, and faculty offices.",
    x: 1040,
    y: 150,
    hours: "8:00 AM - 7:00 PM",
    facilities: "ECE & Mechanical Labs, Classrooms, Research Labs",
    styleType: "ab2-box",
    gmapsQuery: "Academic Block 2 AB2 VIT Bhopal"
  },
  {
    id: "archblock",
    name: "Architecture Block",
    category: "academic",
    catLabel: "Academic",
    icon: "🏢",
    tagline: "School of Architecture & Design Studios",
    desc: "Modern multi-storey building with a prominent floor-to-ceiling glass curtain wall facade, architecture studios, design workshops, and exhibition gallery.",
    x: 980,
    y: 330,
    hours: "8:00 AM - 7:00 PM",
    facilities: "Design Studios, Model Making Lab, CAD Labs, Exhibition Space",
    styleType: "archblock-real",
    gmapsQuery: "Architecture Block VIT Bhopal"
  },
  {
    id: "library",
    name: "Central Library",
    category: "academic",
    catLabel: "Academic",
    icon: "📚",
    tagline: "Central Knowledge Hub & Reading Halls",
    desc: "Spacious central library featuring physical book stacks, digital research databases, quiet study zones, and discussion rooms.",
    x: 770,
    y: 310,
    hours: "8:00 AM - 10:00 PM",
    facilities: "Quiet Reading Zones, E-Resource Hub, Book Issue Desk, Wi-Fi",
    styleType: "library-round",
    gmapsQuery: "Central Library VIT Bhopal"
  },

  /* --- FOOD STALLS & EATERIES --- */
  {
    id: "mayuri_ab",
    name: "Mayuri (AB Side)",
    category: "food",
    catLabel: "Food Stall",
    icon: "🍛",
    tagline: "Popular Cafeteria near AB1 Entrance",
    desc: "Serves daily thalis, North & South Indian meals, snacks, samosas, and cold beverages right near Academic Block 1.",
    x: 670,
    y: 190,
    hours: "8:00 AM - 8:30 PM",
    facilities: "Thali Meals, Parathas, Cold Drinks, Snacks, Tea & Coffee",
    styleType: "food-stall",
    gmapsQuery: "Mayuri Canteen AB1 VIT Bhopal"
  },
  {
    id: "ub_ab",
    name: "UB / Under the Tree (AB Side)",
    category: "food",
    catLabel: "Food Stall",
    icon: "🌳",
    tagline: "Iconic Outdoor Student Hangout & Cafe",
    desc: "Famous student meetup spot under the trees near AB1, serving fresh tea, coffee, Maggi, patties, and quick bites.",
    x: 710,
    y: 250,
    hours: "8:30 AM - 9:00 PM",
    facilities: "Special Tea, Maggi, Patties, Sandwiches, Outdoor Seating",
    styleType: "food-stall",
    gmapsQuery: "Under the Tree UB VIT Bhopal"
  },
  {
    id: "mayuri_ab2",
    name: "Mayuri (AB2 Side)",
    category: "food",
    catLabel: "Food Stall",
    icon: "🍱",
    tagline: "Quick Eatery near AB2 Block",
    desc: "Convenient snack stall located adjacent to Academic Block 2 for quick lunch breaks, wraps, rolls, and refreshments.",
    x: 1080,
    y: 210,
    hours: "9:00 AM - 7:30 PM",
    facilities: "Quick Bites, Rolls, Fresh Juices, Coffee",
    styleType: "food-stall",
    gmapsQuery: "Mayuri AB2 VIT Bhopal"
  },
  {
    id: "ab_dakshin",
    name: "AB Dakshin",
    category: "food",
    catLabel: "Food Stall",
    icon: "🥟",
    tagline: "Authentic South Indian Tiffin Corner",
    desc: "Speciality stall serving piping hot crisp Dosas, Idlis, Vadas, Uttapams, and authentic Filter Coffee.",
    x: 840,
    y: 220,
    hours: "8:00 AM - 8:00 PM",
    facilities: "Masala Dosa, Idli Sambhar, Filter Coffee, Vada",
    styleType: "food-stall",
    gmapsQuery: "AB Dakshin VIT Bhopal"
  },
  {
    id: "bistro",
    name: "The Bistro",
    category: "food",
    catLabel: "Food Stall",
    icon: "🍕",
    tagline: "Continental, Pastas, Burgers & Shakes",
    desc: "Modern campus bistro offering pizzas, grilled burgers, pasta bowls, thick milkshakes, and cafe desserts.",
    x: 580,
    y: 380,
    hours: "11:00 AM - 10:00 PM",
    facilities: "Woodfire Pizza, Pasta, Burgers, Shakes, Waffles",
    styleType: "food-stall",
    gmapsQuery: "Bistro VIT Bhopal"
  },
  {
    id: "foodcourt",
    name: "Central Food Court (Containers)",
    category: "food",
    catLabel: "Food Hub",
    icon: "🍽️",
    tagline: "Multi-Cuisine Container Kiosks & Mayuri's",
    desc: "Vibrant central food hub featuring signature orange container stalls under a white geometric triangular roof, Kathi rolls, ice cream parlours, and indoor seating.",
    x: 500,
    y: 440,
    hours: "7:00 AM - 11:30 PM",
    facilities: "Kathi Rolls, Chinese Wok, Ice Cream, Momos, Seating",
    styleType: "foodcourt-real",
    gmapsQuery: "Central Food Court VIT Bhopal"
  },

  /* --- HOSTELS --- */
  {
    id: "boyshostel",
    name: "Boys Hostels (Blocks 1-6)",
    category: "hostel",
    catLabel: "Hostel",
    icon: "🏠",
    tagline: "Blocks 1-6 Accommodation & Mess",
    desc: "Multi-storey student residence blocks (Mayuri, Kshipra, Narmada, Tapti, Kaveri, Godavari) equipped with AC/Non-AC rooms, student mess, gym, and Wi-Fi.",
    x: 1060,
    y: 590,
    hours: "24 Hours (Student In-time Rules)",
    facilities: "Student Mess, Wi-Fi, Gym, Table Tennis, Night Canteen",
    styleType: "hostels-boys",
    gmapsQuery: "Boys Hostel VIT Bhopal"
  },
  {
    id: "girlshostel",
    name: "Girls Hostels (Blocks 1 & 2)",
    category: "hostel",
    catLabel: "Hostel",
    icon: "👩‍🎓",
    tagline: "Sarojini & Kalpana Residence",
    desc: "Secure girls hostel complex featuring modern dining halls, study lounges, indoor sports rooms, and 24/7 security.",
    x: 810,
    y: 615,
    hours: "24 Hours (Student In-time Rules)",
    facilities: "Dining Hall, Night Canteen, Reading Room, Wi-Fi",
    styleType: "hostels-girls",
    gmapsQuery: "Girls Hostel VIT Bhopal"
  },

  /* --- SERVICES & OTHERS --- */
  {
    id: "parcel",
    name: "Parcel Pickup Hub",
    category: "services",
    catLabel: "Services",
    icon: "📦",
    tagline: "Amazon, Flipkart & DTDC Courier Counter",
    desc: "Central parcel collection desk where all online ecommerce deliveries and courier packages arrive for students.",
    x: 635,
    y: 445,
    hours: "10:00 AM - 6:00 PM",
    facilities: "OTP Package Collection, Courier Drop-off",
    styleType: "parcel-box",
    gmapsQuery: "Parcel Pickup VIT Bhopal"
  },
  {
    id: "pharmacy",
    name: "Health Centre & Pharmacy",
    category: "services",
    catLabel: "Medical",
    icon: "🩺",
    tagline: "24/7 Medical Care & Pharmacy",
    desc: "On-campus medical center with resident doctor, first-aid, emergency beds, pharmacy, and 24/7 ambulance service.",
    x: 295,
    y: 345,
    hours: "24 Hours Open",
    facilities: "Doctor Consultation, Emergency Care, Medicine Store",
    styleType: "health-red",
    gmapsQuery: "Health Centre VIT Bhopal"
  },
  {
    id: "sports",
    name: "Sports Complex & Field",
    category: "sports",
    catLabel: "Sports",
    icon: "⚽",
    tagline: "Football Pitch, Basketball & Volleyball Courts",
    desc: "Outdoor sports complex featuring a full football ground, basketball court, volleyball ground, and athletic track.",
    x: 570,
    y: 615,
    hours: "6:00 AM - 9:00 PM",
    facilities: "Football Field, Basketball Court, Athletic Track",
    styleType: "sports-field",
    gmapsQuery: "Sports Ground VIT Bhopal"
  },
  {
    id: "maingate",
    name: "Main Entrance Gate",
    category: "services",
    catLabel: "Services",
    icon: "🛡️",
    tagline: "24/7 Main Security Gate",
    desc: "Primary entrance checkpoint to VIT Bhopal campus with security boom barriers, visitor entry counter, and auto/cab stand.",
    x: 225,
    y: 777,
    hours: "24 Hours Open",
    facilities: "Security Control, Visitor Pass Desk, Cab Pickup",
    styleType: "gate-box",
    gmapsQuery: "Main Gate VIT Bhopal"
  }
];

// Graph Nodes & Edges for Turn-by-Turn Route Navigation
const CAMPUS_GRAPH = {
  nodes: {
    maingate: { x: 225, y: 777 },
    road_1: { x: 400, y: 720 },
    road_2: { x: 400, y: 450 },
    pharmacy: { x: 295, y: 345 },
    bistro: { x: 580, y: 380 },
    road_north: { x: 400, y: 250 },
    road_top: { x: 480, y: 180 },
    mayuri_ab: { x: 670, y: 190 },
    ub_ab: { x: 710, y: 250 },
    ab1: { x: 760, y: 165 },
    ab_dakshin: { x: 840, y: 220 },
    mayuri_ab2: { x: 1080, y: 210 },
    ab2: { x: 1040, y: 150 },
    archblock: { x: 980, y: 330 },
    library: { x: 770, y: 310 },
    foodcourt: { x: 500, y: 440 },
    parcel: { x: 635, y: 445 },
    girlshostel: { x: 810, y: 615 },
    sports: { x: 570, y: 615 },
    boyshostel: { x: 1060, y: 590 }
  },
  edges: [
    { from: "maingate", to: "road_1", dist: 180 },
    { from: "road_1", to: "road_2", dist: 270 },
    { from: "road_1", to: "sports", dist: 190 },
    { from: "road_2", to: "pharmacy", dist: 140 },
    { from: "road_2", to: "foodcourt", dist: 100 },
    { from: "foodcourt", to: "bistro", dist: 90 },
    { from: "foodcourt", to: "parcel", dist: 135 },
    { from: "road_2", to: "road_north", dist: 200 },
    { from: "road_north", to: "road_top", dist: 110 },
    { from: "road_top", to: "mayuri_ab", dist: 190 },
    { from: "mayuri_ab", to: "ab1", dist: 90 },
    { from: "mayuri_ab", to: "ub_ab", dist: 70 },
    { from: "ab1", to: "ab_dakshin", dist: 100 },
    { from: "ab1", to: "library", dist: 140 },
    { from: "ab1", to: "ab2", dist: 280 },
    { from: "ab2", to: "mayuri_ab2", dist: 70 },
    { from: "ab2", to: "archblock", dist: 180 },
    { from: "archblock", to: "boyshostel", dist: 260 },
    { from: "parcel", to: "girlshostel", dist: 230 },
    { from: "girlshostel", to: "boyshostel", dist: 250 },
    { from: "sports", to: "girlshostel", dist: 240 }
  ]
};
